apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-service
  labels:
    app: kvstore
spec:
  selector:
    matchLabels:
      app: kvstore
  replicas: 1
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
        - name: kvstore
          image: ../bazel/diypaxos:diypaxos_image
          ports:
            - name: kvstore-service
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: headless-kvstore
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kvstore