apiVersion: v1
kind: Service
metadata:
  name: headless-kvstore
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kvstore

---
apiVersion: v1
kind: Service
metadata:
  name: headless-kvstore-ext
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kvstore
  type: LoadBalancer
  