apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kvstore-service
  labels:
    app: kvstore
spec:
  selector:
    matchLabels:
      app: kvstore
  serviceName: "nginx"
  replicas: 6
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
        - name: kvstore
          image: "img"
          imagePullPolicy: Never
          ports:
            - name: kvstore-service
              containerPort: 8080